language: python
python:
    - 3.7

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-7
    - g++-7
    - gfortran

before_install:
    - pip3 install -U pip setuptools
    - pip3 install coveralls
    - git clone https://github.com/tschijnmo/DummyRDD.git
    - cd DummyRDD; python3 setup.py install; cd ..
    - export CC=gcc-7
    - export CXX=g++-7
    - git clone --recursive https://github.com/tschijnmo/drudge.git
    - cd drudge; python3 setup.py install; cd ..

install:
    - python3 setup.py install

script:
    - export DUMMY_SPARK=1
    - cd tests
    - coverage run --source=gristmill -m pytest -sv

after_success:
    - coveralls

